---
streets:
  - name: ул. Петра Мстиславца
    keywords: [м, мст, мстис, мстисл, мстислав, мстиславц, мстиславца, петр, петра]
    buildings:
      '1': mst1
      '2': mst2
  - name: ул. Кирилла Туровского
    keywords: [т, кир, кирил, кирила, кирилла, тур, туров, туровс, туровского, туровский]
    buildings:
      '2': tur2
apartments:
  mst1-1: 1
  mst1-2: 46
  mst2-1: 1
  mst2-2: 41
  tur2: [1, 4, 8, 12, 16, 20, 24, 28, 32, 36]
