---
responses:
  - name: Карта Маяка Минска
    photo: map_mayak.jpg
    keywords: ['карта', 'маяк*', map]
start: >
  Привет! Это навигатор по Маяку Минска. Здесь есть почти
  все заведения нашего района. Для поиска введите ключевое
  слово или слова. Например, «суши» или «аптека».

  Есть карта по слову «карта». Наконец, можно найти дом по
  «м4» (Мстиславца 4) или «т10» (Туровского 10), а то и квартиру
  по «м4 33».
home: Привет! Введи, что ищешь, или нажми кнопку.
not_found: >
  По запросу «%s» ничего не найдено. Если видите это заведение,
  попробуйте другой запрос или нажмите кнопку, чтобы добавить его в базу.

buttons:
  - [Мстиславца, Туровского, Скорины 5]
  - [🗺️, 🍽️,  🍺, 🛒, 💊, 🐈]
  - [💐, 🍷, 💅, ✂️, 💳, ✉️]

synonims:
  еда: [🍽️]
  карта: [🗺️]
  аптека: [⚕️, 💊]
  банк: [💳]
  почта: [📯, ✉️]
  зоо: [🐈]
  цветы: [💐]
  бар: [🍺]
  продукты: [🛒]
  парикмахерская: [✂️]
  фонтан: [⛲]
  вино: [🍷]
  маникюр: [💅]

tags:
  shop=florist: [цветы, розы, роза, тюльпан, тюльпаны, букет, букеты]
  shop=convenience: [продукты]
  shop=supermarket: [супермаркет, продукты, магазин]
  shop=clothes: [одежда, одежды, верхняя, верхней]
  shop=hairdresser: [парикмахерская, стрижка, салон, стрижки, барбер, барбершоп, шоп, цирюльник]
  shop=beauty: [салон красоты, салон, красоты, стрижка, парикмахерская]
  shop=bakery: [пекарня, выпечка]
  shop=furniture: [мебель, мебельный]
  shop=shoes: [обувной, обуви, обувь, ботинки, сапоги]
  shop=jewelry: [ювелирный, золото, кольца, ювелирка, ювелир]
  shop=books: [книжный, книги]
  shop=greengrocer: [овощной, овощи, фрукты, зелень, яблоки, перцы, апельсины, мандарины]
  shop=travel_agency: [турагентство, тур, туризм, агентство, путешествия, билеты]
  shop=chemist: [бытовая химия, бытовая, химия, порошок, стиральный, шампунь, гель, душа, для]
  shop=pet: [зоомагазин, зоотовары, зоо, кошке, кошек, собаке, собак, корм]
  shop=nail_salon: [ноготочки, ногтевой, салон, ногти, ногтей, маникюр, педикюр]
  amenity=pharmacy: [аптека, лекарства, таблетки, маски, маска]
  amenity=cafe: [кафе, еда]
  amenity=restaurant: [ресторан, еда]
  amenity=school: [школа]
  amenity=fast_food: [фастфуд, фаст, фуд, еда]
  amenity=bank: [банк, кредит, кредиты, деньги, валюта]
  amenity=atm: [банкомат, atm]
  amenity=toilets: [туалет, wc, мж]
  amenity=post_office: [почта, пошта, белпочта, белпошта, письма, посылки, бандероль, посылка, письмо]
  amenity=post_box: [почтовый ящик, почтовый, ящик]
  amenity=kindergarten: [детский сад, детский, сад, детсад, ясли]
  amenity=bar: [бар, пиво, паб]
  amenity=pub: [бар, пиво, паб]
  amenity=hospital: [больница, госпиталь, доктор, врач]
  amenity=clinic: [клиника, доктор, врач]
  amenity=fountain: [фонтан]
  amenity=dentist: [дантист, зубы, зубной, врач]
  amenity=library: [библиотека]

suggest_tags:
  - shop=florist
  - amenity=pharmacy
  - shop=convenience
  - amenity=cafe
  - amenity=bar
  - shop=clothes
  - shop=hairdresser
  - shop=beauty
  - shop=nail_salon

skip: [а, и, к, в, по, из, от, во, ко, ул, улица, где, как, что, чем, чём, пройти, найти, находится]

save: 💾 Сохранить
cancel: ❌ Отменить
default_link: сайт
poi_list: 'По запросу «%s» нашли несколько заведений:'
location: Спасибо, на ближайшие пять минут учтём ваше местоположение при поиске.
message: Введите сообщение — его увидят модераторы.
do_reply: Ответьте на сообщение ниже с цитированием, чтобы адресат получил ваш ответ.

new_poi:
  name: 'Спасибо, что добавляете заведение! Введите название как на вывеске:'
  name_too_short: 'Слишком короткое название, введите ещё раз:'
  location: 'Теперь прикрепите местоположение с координатами заведения:'
  no_location: 'Нажмите на скрепку и прикрепите местоположение (location):'
  keywords: 'И последнее из обязательного: введите побольше ключевых слов для поиска этого заведения. Например, «кафе еда багет багеты круассаны круассан кофе».'
  no_keywords: 'Пожалуйста, можно побольше слов:'
  confirm: Вот как выглядит новое заведение. Если нужно, добавьте полей, особенно полезны фотографии и время работы.
  confirm2: |
    Нажмите на команду или пришлите фотографию, чтобы поправить заведение. Закончите — жмите «Сохранить».
    Вместо редактирования можете просто ввести замечание для модераторов.
  cancel: Не проблема, добавим в другой раз.

editor:
  photo: Спасибо за фотографию! Это вид откуда?
  upload_file: Не удалось загрузить файл, попробуйте ещё раз.
  dash: Введите «-» без кавычек, если нужно очистить поле.
  desc: Введите новое описание.
  tag: Выберите тип заведения или введите тег как в OpenStreetMap. Например, amenity=cafe или shop=convenience. Если не знаете, что это, то лучше и не надо.
  comment: Введите новый комментарий, можно многострочный.
  keywords: Ключевые слова можно только добавлять. Введите новые слова через пробел.
  location: Прикрепите местоположение или скопируйте lat,lon с сайта.
  house: Выберите дом.
  address: Введите помещение и/или этаж, без адреса.
  cancel: Оставить как есть
  wifi: Есть ли в заведении бесплатный Wi-Fi?
  cards: Можно ли оплатить покупки или услуги картой Visa / Mastercard?
  phones: Введите все телефоны через точку с запятой, каждый начиная с +375.
  links: 'Введите название из одного слова и ссылку через пробел, например: «сайт https://ya.ru/». Если название уже есть, ссылка будет заменена на новую. Для удаления введите только название существующей ссылки.'
  hours: 'Введите часы работы. Примеры: «8-20», «пн-пт 10-19:30», «пн-чт 10-20 обед 13-14, пт-вс 10-18».'
  sent: Ваше замечание отправлено модераторам.
  saved: Спасибо, заведение сохранено.
  sent: Спасибо, ваши изменения отправлены на модерирование. Скоро их посмотрим и применим.
  cant_delete: Удалять заведения могут только модераторы. Напишите им прямо здесь.

queue:
  empty: Очередь пуста, вы свободны!
  field: 'Запрос от {user}: у заведения «{name}» уточнить поле {field}.'
  message: 'Пользователь {user} попросил уточнить заведение «{name}»:'
  look: 🔍 Карточка
  apply: ✅ Применить
  delete: ❌ Удалить
  applied: Применили
  deleted: Удалили
  added: 'Очередь исправлений удлиннилась: нажмите /queue, чтобы её разобрать.'
