---
responses:
  - name: Карта Маяка Минска
    photo: map_mayak.jpg
    keywords: ['карта', 'маяк*', map]
bbox: [27.639915, 53.925492, 27.659763, 53.935321]
start: >
  Привет! Это навигатор по Маяку Минска. Здесь есть
  все заведения и подъезды нашего района. Для поиска введите ключевое
  слово или слова. Например, «суши» или «аптека».

  Заведения можно поправить, в том числе добавить новые.
  Также, по слову «карта» вы получите карту района, а по адресу
  (например, «мст 4 144») — подъезд и этаж.

  Другой похожий бот — каталог Маяка: @mayak_minska_bot.
home: Привет! Введи, что ищешь, или нажми кнопку.
not_found: >
  По запросу «%s» ничего не найдено. Если видите это заведение,
  попробуйте другой запрос или нажмите кнопку, чтобы добавить его в базу.
  Или нажмите на /random, если не знаете, что выбрать.
help: |
  Это бот для поиска заведений и квартир Маяка Минска. Он умеет
  находить всё — только напишите ему одно-два ключевых слова.
  Например, «танцы». Для удобства внизу есть кнопки с улицами
  и некоторыми видами заведений. Немного статистики:

  — В базе {entrances} подъездов в {buildings} домах.
  — И {pois} магазинов, заведений и огранизаций.

  Здесь не получится покопаться в каталоге и найти интересненькое
  (за этим подпишитесь на каталог Маяка @mayak_minska_bot). Но
  попробуйте посмотреть на несколько случайных заведений из
  базы: /random. И нажимайте на кнопку «Похожее» в карточках
  заведений: это точнее, чем вводить слова. Например, от карточки
  языковой школы можно найти все остальные языковые школы.

  Чтобы списки показывали ближайшие заведения, пришлите свои
  координаты (скрепка → «Местоположение»). Все ваши данные бот
  забудет через 5-10 минут, а логи пишутся обезличенно,
  так что не волнуйтесь за приватность.

  Если в данных что-то не так (отсутствует заведение, опечатка
  в телефоне и т.п.) — нажмите /msg и напишите модераторам, они
  поправят. Бота написал Илья Зверев @ilyazver.

buttons:
  - [Мстиславца, Туровского, Скорины 5]
  - [🗺️, 🍽️,  🍺, 🛒, 💊, 🐈]
  - [💐, 🍷, 💅, ✂️, 💳, ✉️]

synonims:
  еда: [🍽️]
  карта: [🗺️]
  аптека: [⚕️, 💊]
  банк: [💳]
  почта: [📯, ✉️]
  зоо: [🐈]
  цветы: [💐]
  бар: [🍺]
  продукты: [🛒]
  парикмахерская: [✂️]
  фонтан: [⛲]
  вино: [🍷]
  маникюр: [💅]
  '/random': [🎲]

skip: [а, и, к, в, по, из, от, во, ко, ул, улица, где, как, что, чем, чём, для, пройти, найти, находится]

save: 💾 Сохранить
cancel: ❌ Отменить
default_link: сайт
poi_list: 'По запросу «%s» нашли несколько заведений:'
poi_not_full: Список неполный, нажмите последнюю кнопку для запроса всех {total_count}. Пришлите координаты, чтобы посмотреть ближайшие.
poi_too_many: Список неполный, но все {total_count} никак не поместятся. Пришлите координаты, чтобы посмотреть ближайшие.
location: Спасибо, на ближайшие пять минут учтём ваше местоположение при поиске.
message: Введите сообщение — его увидят модераторы.
do_reply: Ответьте на сообщение ниже с цитированием, чтобы адресат получил ваш ответ.
maintenance: 'База временно закрыта на запись, извините. Напишите модераторам, что вы хотите поправить: /msg'

new_poi:
  name: 'Спасибо, что добавляете заведение! Введите название как на вывеске:'
  name_too_short: 'Слишком короткое название, введите ещё раз:'
  location: 'Теперь прикрепите местоположение с координатами заведения:'
  no_location: 'Нажмите на скрепку и прикрепите местоположение (location):'
  location_out: 'Координаты слишком далеко от Маяка. Найдите что-нибудь поближе или отмените.'
  keywords: 'И последнее из обязательного: введите побольше ключевых слов для поиска этого заведения. Например, «кафе еда багет багеты круассаны круассан кофе».'
  no_keywords: 'Пожалуйста, можно побольше слов:'
  confirm: Вот как выглядит новое заведение. Если нужно, добавьте полей, особенно полезны фотографии и время работы.
  confirm2: |
    Нажмите на команду или пришлите фотографию, чтобы поправить заведение. Закончите — жмите «Сохранить».
  cancel: Не проблема, добавим в другой раз.

editor:
  photo: Спасибо за фотографию! Это вид откуда?
  upload_fail: Не удалось загрузить файл, попробуйте ещё раз.
  dash: Введите «-» без кавычек, если нужно очистить поле.
  name: Введите новое название.
  desc: Введите новое описание.
  tag: Выберите тип заведения или введите тег как в OpenStreetMap. Например, amenity=cafe или shop=convenience. Если не знаете, что это, то лучше и не надо.
  comment: Введите новый комментарий, можно многострочный.
  keywords: Ключевые слова можно только добавлять. Введите новые слова через пробел.
  location: Прикрепите местоположение или скопируйте lat,lon с сайта.
  house: Выберите дом.
  address: Введите помещение и/или этаж, без адреса.
  cancel: Оставить как есть
  wifi: Есть ли в заведении бесплатный Wi-Fi?
  cards: Можно ли оплатить покупки или услуги картой Visa / Mastercard?
  phones: Введите все телефоны через точку с запятой, каждый начиная с +375.
  links: 'Введите название из одного слова и ссылку через пробел, например: «сайт https://ya.ru/». Если название уже есть, ссылка будет заменена на новую. Для удаления введите только название существующей ссылки.'
  hours: 'Введите часы работы. Примеры: «8-20», «пн-пт 10-19:30», «пн-чт 10-20 обед 13-14, пт-вс 10-18».'
  sent: Ваше замечание отправлено модераторам.
  saved: Спасибо, заведение сохранено.
  sent: Спасибо, ваши изменения отправлены на модерирование. Скоро их посмотрим и применим.
  message: Введите сообщение, чтобы передать модераторам.
  msg_sent: Спасибо, ваше замечание отправлено модераторам.
  delete: Введите причину для удаления.
  deleted: Заведение удалено.
  deleted2: Заведение удалено из базы.
  cant_restore: 'Восстановить заведение может только модератор. Напишите им: /msg'
  restored: Заведение снова можно найти.

queue:
  empty: Очередь пуста, вы свободны!
  field: 'Запрос от {user}: у заведения «{name}» уточнить поле {field}.'
  message: 'Пользователь {user} попросил уточнить заведение «{name}»:'
  look: 🔍 Карточка
  apply: ✅ Применить
  validated: ✔️ Проверено
  delete: ❌ Нет, спасибо
  applied: Применили
  deleted: Удалили
  validated_ok: Заведение проверено.
  added: 'Очередь исправлений удлиннилась: нажмите /queue, чтобы её разобрать.'
  new_poi: Кто-то добавил заведение выше, проверьте его и нажмите кнопку.
