---
responses:
  - name: Карта Маяка Минска
    photo: map_mayak.jpg
    keywords: ['карта', 'маяк*', map]

buttons:
  - [Мстиславца, Туровского, Скорины 5]
  - [🗺️, 🍽️, 🛒, 💊, 💐, 🐈]
  - [☕, 🍺, 💅, ✂️, 💳, ✉️]

synonims:
  еда: [🍽️]
  карта: [🗺️]
  аптека: [⚕️, 💊]
  банк: [💳]
  почта: [📯, ✉️]
  зоо: [🐈]
  цветы: [💐]
  пиво: [🍺]
  продукты: [🛒]
  парикмахерская: [✂️]
  кофейня: [☕]
  фонтан: [⛲]
  вино: [🍷]
  маникюр: [💅]
  '/random': [🎲]

skip: [а, и, к, в, по, из, от, во, ко, ул, улица, где, как, что, чем, чём, для, пройти, найти, находится]

start: >
  Привет! Это навигатор по Маяку Минска. Здесь есть все заведения и подъезды нашего района. Для поиска введите ключевое слово или слова. Например, «суши» или «аптека».

  Заведения можно поправить, в том числе добавить новые.  Также, по слову «карта» вы получите карту района, а по адресу (например, «мст 4 144») — подъезд и этаж. Отмечайте заведения звёздочками, чтобы помочь другим. И нажмите «/», чтобы посмотреть список команд.

  Другой похожий бот — каталог Маяка: @mayak_minska_bot.

help: |
  Это бот для поиска заведений и квартир Маяка Минска. Он умеет находить всё — только напишите ему одно-два ключевых слова. Например, «танцы». Для удобства внизу есть кнопки с улицами и некоторыми видами заведений. Немного статистики:

  — В базе {entrances} подъездов в {buildings} домах.
  — И {pois} магазинов, заведений и огранизаций.
  — Люди поставили {stars} звёзд заведениям.

  Здесь не получится покопаться в каталоге и найти интересненькое (за этим подпишитесь на каталог Маяка @mayak_minska_bot). Но попробуйте посмотреть на несколько случайных заведений из базы: /random. И нажимайте на кнопку «Похожее» в карточках заведений: это точнее, чем вводить слова. Например, от карточки языковой школы можно найти все остальные языковые школы.

  Чтобы списки показывали ближайшие заведения, пришлите свои координаты (скрепка → «Местоположение»). Все ваши данные бот забудет через 5-10 минут, а логи пишутся обезличенно, так что не волнуйтесь за приватность.

  Если в данных что-то не так (отсутствует заведение, опечатка в телефоне и т.п.) — нажмите /msg и напишите модераторам, они поправят. Или поправьте сами. Бота написал Илья Зверев @ilyazver.
