home: Привет! Введи, что ищешь, или нажми кнопку.
not_found: >
  По запросу «%s» ничего не найдено. Если видите это заведение,
  попробуйте другой запрос или нажмите кнопку, чтобы добавить его в базу.
  Или нажмите на /random, если не знаете, что выбрать.
save: Сохранить
cancel: Отменить
default_link: сайт
open_link: Открыть сайт
poi_links: Ссылки
has_wifi: Есть бесплатный Wi-Fi.
accepts_cards: Можно оплатить картой.
no_cards: Оплата только наличными.
open_247: Открыто круглосуточно.
now_open: Открыто сегодня до %s
next_open: '{day} работает с {hour}.'
now_closed: Закрыто. Откроется {day} в {hour}.
tomorrow: завтра
relative_days: [в понедельник, во вторник, в среду, в четверг, в пятницу, в субботу, в воскресенье]
poi_list: 'По запросу «%s» нашли несколько заведений:'
poi_not_full: Список неполный, нажмите последнюю кнопку для запроса всех {total_count}. Пришлите координаты, чтобы посмотреть ближайшие.
poi_too_many: Список неполный, но все {total_count} никак не поместятся. Пришлите координаты, чтобы посмотреть ближайшие.
all: Все
poi_in_house: Заведения в этом доме
query_fail: Что-то пошло не так — повторите запрос, пожалуйста.
no_poi_key: Нет заведения с таким номером.
no_poi_in_house: Заведений нет.
choose_floor: В этом доме заведения на нескольких этажах. Выберите этаж.
location: Спасибо, на ближайшие пять минут учтём ваше местоположение при поиске.
no_similar: Нет похожих заведений
message: Введите сообщение — его увидят модераторы.
message_self: Себе сообщения слать нельзя.
do_reply: Ответьте на сообщение ниже с цитированием, чтобы адресат получил ваш ответ.
reply_sent: Отправлен ответ на сообщение %s.
star: Отметить
starred: Избранное
no_starred: Вы пока не отметили ни одного заведения.
no_popular: Популярных заведений пока нет. Отмечайте хорошее звёздочками!
loc_btn: Координаты
edit_poi: Поправить
notify_mods: Сообщить модераторам
add_poi: Добавить заведение
similar: Похожие
maintenance: 'База временно закрыта на запись, извините. Напишите модераторам, что вы хотите поправить: /msg'
on_street: 'Выберите дом по %s:'
no_building: Нет дома {house} по {street}
send_apt: Пришлите номер квартиры, если хотите.
apt_number: 'Номер квартиры %s должен быть числом. Вот карточка для дома:'
apartment: Квартира %s.
floor: Квартира {apt} на {floor} этаже.

new_poi:
  name: 'Спасибо, что добавляете заведение! Введите название как на вывеске:'
  name_too_short: 'Слишком короткое название, введите ещё раз:'
  location: 'Теперь прикрепите местоположение с координатами заведения:'
  no_location: 'Нажмите на скрепку и прикрепите местоположение (location):'
  location_out: 'Координаты слишком далеко от Маяка. Найдите что-нибудь поближе или отмените.'
  keywords: 'И последнее из обязательного: введите побольше ключевых слов для поиска этого заведения. Например, «кафе еда багет багеты круассаны круассан кофе».'
  no_keywords: 'Пожалуйста, можно побольше слов:'
  confirm: Вот как выглядит новое заведение. Если нужно, добавьте полей, особенно полезны фотографии и время работы.
  confirm2: |
    Нажмите на команду или пришлите фотографию, чтобы поправить заведение. Закончите — жмите «Сохранить».
  cancel: Не проблема, добавим в другой раз.
  latlon: Взять lat,lon с сайта

editor:
  panel:
    desc: Описание
    keywords: Ключевые слова
    tag: OSM-тег
    house: Адрес
    floor: Этаж
    addr: Местонахождение
    hours: Часы работы
    loc: Координаты
    loc_browse: смотреть
    phone: Телефоны
    wifi: Есть ли Wi-Fi
    card: Оплата картой
    links: Ссылки
    none: нет
    comment: Комментарий
    photo: Фотографии
    photo_both: обе
    photo_out: только вход
    photo_in: только внутри
    photo_comment: залейте замену или /ephoto для просмотра, /eout для копирования фото снаружи
    deleted: Удалено
    restore: Восстановить
    delete: Удалить
    msg: Написать модераторам
  photo: Спасибо за фотографию! Это вид откуда?
  upload_fail: Не удалось загрузить файл, попробуйте ещё раз.
  dash: Введите «-» без кавычек, если нужно очистить поле.
  name: Введите новое название.
  empty_name: Имя нельзя очищать
  desc: Введите новое описание.
  tag: Выберите тип заведения или введите тег как в OpenStreetMap. Например, amenity=cafe или shop=convenience. Если не знаете, что это, то лучше и не надо.
  tag_format: Тег должен быть в виде ключ=значение, а не %s.
  comment: Введите новый комментарий, можно многострочный.
  keywords: Ключевые слова можно только добавлять. Введите новые слова через пробел.
  location: Прикрепите местоположение или скопируйте lat,lon с сайта.
  house: Выберите дом.
  floor: 'Выберите этаж или введите название нового этажа. Слово «этаж» пишите: например, «5 этаж».'
  address: Введите помещение и/или номер входа, без адреса и этажа.
  cancel: Оставить как есть
  wifi: Есть ли в заведении бесплатный Wi-Fi?
  cards: Можно ли оплатить покупки или услуги картой Visa / Mastercard?
  phones: Введите все телефоны через точку с запятой, каждый начиная с +375.
  links: 'Введите название из одного слова и ссылку через пробел, например: «сайт https://ya.ru/». Если название уже есть, ссылка будет заменена на новую. Для удаления введите только название существующей ссылки.'
  links_have: 'Ссылки, которые есть:'
  no_links: Пока нет ни одной ссылки.
  instagram: инстаграм
  link_replace:
    вконтакте: vk
    вк: vk
    vkontakte: vk
    facebook: фейсбук
  hours: 'Введите часы работы. Примеры: «8-20», «пн-пт 10-19:30», «пн-чт 10-20 обед 13-14, пт-вс 10-18».'
  hours_abbr: [пн, вт, ср, чт, пт, сб, вс]
  hours_break: обед
  hours_format: 'Непонятный формат: "%s".'
  sent: Ваше замечание отправлено модераторам.
  saved: Спасибо, заведение сохранено.
  sent: Спасибо, ваши изменения отправлены на модерирование. Скоро их посмотрим и применим.
  message: Введите сообщение, чтобы передать модераторам.
  cant_message: Вы же модератор, сделайте сами!
  other_msg: Нажмите на любую команду из списка выше, или /msg для связи с модератором.
  msg_sent: Спасибо, ваше замечание отправлено модераторам.
  delete: Введите причину для удаления.
  deleted: Заведение удалено.
  deleted2: Заведение удалено из базы.
  delete_twice: Нельзя удалить заведение дважды.
  just_deleted: 'Только что удалили заведение /poi{id}: {reason}'
  just_added: 'Только что добавили заведение /poi{id}: "{name}"'
  error_save: 'Ошибка при сохранении данных: %s. Попробуйте ещё раз или отмените.'
  saved_look: Посмотреть заведение
  saved_add: Добавить новое
  cant_restore: 'Восстановить заведение может только модератор. Напишите им: /msg'
  restored: Заведение снова можно найти.
  wrong_attr: Атрибут %s пока не редактируем.
  bool_yes: да
  bool_no: нет
  unknown: неизвестно
  bool_true: Есть
  bool_false: Нет
  bool_none: ХЗ
  next_page: Ещё
  no_photos_around: Нет фотографий вокруг.
  choose_photo: Выберите фотографию.
  photo_out: Снаружи
  photo_in: Изнутри
  photo_del: Удалить
  photo_lost: Ваша фотография потерялась. Попробуйте ещё раз.
  photo_deleted: Хорошо, фоточку удалили.
  photo_forgot: Хорошо, фоточку забыли.

queue:
  empty: Очередь пуста, вы свободны!
  field: 'Запрос от {user}: у заведения «{name}» уточнить поле {field}.'
  message: 'Пользователь {user} попросил уточнить заведение «{name}»:'
  look: Карточка
  apply: Применить
  validated: Проверено
  delete: Нет, спасибо
  applied: Применили
  deleted: Удалили
  validated_ok: Заведение проверено.
  added: 'Очередь исправлений удлиннилась: нажмите /queue, чтобы её разобрать.'
  new_poi: Кто-то добавил заведение выше, проверьте его и нажмите кнопку.
  poi_lost: POI пропал, странно.
  poi_lost_del: POI пропал, удаляю запись.
  nothing: ничего
  old: Сейчас
  new: Будет
  missing: Пропало сообщение с таким номером

admin:
  down_json: 'Воспользуйтесь редактором GeoJSON и потом нажмите «Прислать файл» и загрузите результат обратно. Редактор: https://zverik.github.io/point_ed/'
  down_tags: Заполните пропуски в тегах в любом табличном редакторе, потом скачайте результат в формате CSV, нажмите «Прислать файл» и загрузите его сюда.
  maintenance: База заморожена, редактор отключён.
  no_maintenance: База разморожена, можно редактировать заведения
  up_json: Заведения обновлены из файла GeoJSON.
  up_csv: Теги заведений обновлены из файла CSV.

review:
  no_poi_around: Вокруг нет заведений.
  no_floor: Без этажа
  all_floors: Все
  send_loc: Пришлите геопозицию, пожалуйста
  too_many: В доме (на этаже) больше 14 заведений, поэтому целиком их не отобразить. Пришлите геопозицию, чтобы начать осмотр.
  start: Осмотреть заведения
  continue: Продолжить осмотр
  list: Вот какие заведения есть вокруг. Нажмите на кнопку, чтобы отметить заведение проверенным. Для редактирования нажмите «📝» и затем кнопку заведения.
  incomplete: Список может быть неполным. Пришлите геопозицию из другого конца дома, чтобы продолжить.
  absent: нет
  no_hours: нет часов
  stopped: Осмотр закончен. Чтобы продолжить, пришлите геопозицию или поищите дом, в который зашли.
  no_review: Осмотр внезапно закончился, перезапустите
  no_record: Потеряли запись, попробуйте перезапустить
