tags:
  amenity=art_school: [изостудия, студия, школа, рисование, рисования, изо, искусство, искусств, художественная]
  amenity=atm: [банкомат, atm, банк, снять, деньги]
  amenity=bank: [банк, кредит, кредиты, деньги, валюта]
  amenity=bar: [бар, пиво, паб, beer, bar, pub]
  amenity=beauty_school: [школа красоты, школа, обучение, красоты]
  amenity=cafe: [кафе, еда, кофе, гарнир, суп, бистро, ресторан, поесть, салат, горячее]
  amenity=car_rental: [прокат автомобилей, прокат, машин, аренда, авто, автомобилей]
  amenity=childcare: [сад, детсад, детский, ясли, развитие, развивашка, развивашки, детей, обучение]
  amenity=clinic: [клиника, доктор, врач, прививка, медицинская, медицинский, центр, клиника, анализы]
  amenity=coffee: [кофейня, кофе, круассан, круассаны, пирожные, кафе, завтрак, напитки, coffee, выпечка]
  amenity=dancing_school: [танцы, танцев, школа, танцевальная, студия, хореография]
  amenity=dentist: [дантист, зубы, зубной, врач, зуб, стоматолог, стоматология]
  amenity=driving_school: [автошкола, авто, школа, вождения, вождение]
  amenity=fast_food: [фастфуд, фаст, фуд, еда]
  amenity=fountain: [фонтан]
  amenity=hookah_lounge: [кальянная, кальян]
  amenity=hospital: [больница, госпиталь, доктор, врач]
  amenity=kindergarten: [детский сад, детский, сад, детсад, ясли, детсад, детей, детям]
  amenity=language_school: [языки, языковая, школа, иностранный, иностранных, языков, иностранные]
  amenity=library: [библиотека, книги]
  amenity=music_school: [музшкола, музыкальная, музыка, школа]
  amenity=parking: [стоянка, парковка]
  amenity=pharmacy: [аптека, лекарства, таблетки, маски, маска]
  amenity=post_box: [почтовый ящик, почтовый, ящик, письма]
  amenity=post_office: [почта, пошта, письма, посылки, бандероль, посылка, письмо]
  amenity=school: [школа, образование, детей, детям, школьник]
  amenity=toilets: [туалет, wc, мж, '00']
  craft=dressmaker: [пошив платьев, пошив, платьев, платье, платья, ателье]
  craft=electronics_repair: [ремонт, восстановление, техники]
  craft=house: [интерьер, архитектор, дизайн, ремонт, мастер]
  craft=roofer: [кровля, черепица]
  craft=tailor: [ателье]
  leisure=fitness_centre: [фитнес, тренировки, спорт, клуб, фитнесс, фит, качалка, жим, тренер]
  leisure=playground: [детская площадка, детская, площадка]
  leisure=tanning_salon: [солярий, загар, студия, загара]
  natural=tree: [дерево]
  office=company: [офис, компания, компании, организация, организации]
  office=estate_agent: [риэлтор, недвижимость, квартир, квартира, аренда, продажа, съем]
  office=insurance: [страхование, страх, дмс, страховка]
  office=lawyer: [адвокат, адвокаты, юрист, юристы]
  office=property_management: [жэк, жк, тс, тсж, управляющая, компания, обслуживание, обслуживания, жилконтора, центр]
  shop=alcohol: [алкоголь, вино, пиво, водка, коньяк, виски, ликер, спирт, алкоголя, магазин, вина, винный, водочный]
  shop=baby_goods: [детские товары, детские, товары, кресла, стульчики, коляски, сиденья]
  shop=bag: [сумки, сумка, клатч, клатчи, косметичка]
  shop=bakery: [пекарня, выпечка, хлеб, багет, багеты, булка, батон]
  shop=bathroom_furnishing: [сантехника, туалет, ванная, смеситель, смесители, душ, душевая, ванна]
  shop=beauty: [салон красоты, салон, красоты, стрижка, парикмахерская, макияж, укладка, студия]
  shop=instagram_beauty: [инстаграм красоты, салон, красоты, стрижка, макияж, укладка, студия]
  shop=bicycle: [веломагазин, вело, велосипед, велосипеды, велозапчасти, запчасти, байк]
  shop=books: [книжный, книги]
  shop=car_parts: [автозапчасти, авто, запчасти, детали]
  shop=chemist: [бытовая химия, бытовая, химия, порошок, стиральный, шампунь, гель, душа, средство, чистки, мыло]
  shop=clothes: [одежда, одежды, верхняя, верхней, гардероб]
  shop=confectionery: [кондитерская, сласти, сладости, пирожное, пирожные, торт, торты]
  shop=convenience: [продукты, супермаркет, магазин]
  shop=copyshop: [копи-центр, фото, печать, копи, центр, копии, копия, ксерокс, ксерокопии, ксерокопия]
  shop=cosmetics: [косметика, помада, духи, крем, краска, шампунь, волос, лак, ногтей]
  shop=craft: [творчество, творчества]
  shop=curtain: [шторы, салон, штор, текстиль, дома, ткани, ткань, занавески, занавес]
  shop=doors: [двери, дверь, дверей, салон]
  shop=electrical: [электротовары, электрика, электро, товары, запчасти, лампы, лампочки, лампочка, электроника]
  shop=electronics: [бытовая техника, бытовая, техника, электроника]
  shop=erotic: [секс-шоп, секс, интим, шоп, интимные, товары]
  shop=fabric: [ткани, нитки, пряжа, тканей, салон]
  shop=flooring: [напольные покрытия, покрытие, пол, напольные, покрытия, плинтус, плитка, ламинат, линолеум, паркет]
  shop=florist: [цветы, розы, роза, тюльпан, тюльпаны, букет, букеты, флорист, кветки, цветок, открытки, растения, флористика]
  shop=furniture: [мебель, мебельный]
  shop=games: [игры, настолки, настольные, карты]
  shop=gift: [подарок, подарки, открытки, коробки, упаковка, сувенир, сувениры]
  shop=greengrocer: [овощной, овощи, фрукты, зелень, яблоки, перцы, апельсины, мандарины]
  shop=hair_salon: [волосы, волос, парикмахерская]
  shop=hairdresser: [парикмахерская, стрижка, салон, стрижки, барбер, барбершоп, шоп, цирюльник, волосы]
  shop=hardware: [стройтовары, строймаркет, строй, строительство, инструмент, метизы, дрель, молоток, гвозди, саморезы, гайки, болты]
  shop=jewelry: [ювелирный, золото, кольца, ювелирка, ювелир, украшения, украшение, кольцо, серьги]
  shop=lighting: [светильники, лампы, лампа, лампочки, свет, светильник, точечный, торшер, торшеры]
  shop=marriage_salon: [свадебный салон, свадьба, платья, салон, свадебный, наряд]
  shop=massage: [массаж, массажа, салон]
  shop=nail_salon: [маникюр, ноготочки, ногтевой, салон, ногти, ногтей, педикюр, маникюра, педикюра, нейл, nail]
  shop=optician: [оптика, очки, линзы, оправы, очков, зрения, зрение]
  shop=outdoor: [снаряжение, туризм, товары, турист, туристические, рыбалка, охота, поход, похода, охоты, рыбалки, товары]
  shop=pet: [зоомагазин, зоотовары, зоо, кошке, кошек, собаке, собак, корм, ветеринар, ветеринарная]
  shop=seafood: [морепродукты, море, продукты, рыба]
  shop=shoes: [обувной, обуви, обувь, ботинки, сапоги]
  shop=skin_care: [эпиляция и чистка, салон красоты, эпиляция, депиляция, чистка, кожи, лица, ног, спины]
  shop=sports: [спорттовары, спорт, товары, одежда, снаряжение, спортивная, спортивные, обувь]
  shop=stationery: [канцтовары, карандаши, канцелярские, товары, канцелярия, ручки, бумага, блокноты, тетради, тетрадки]
  shop=tattoo: [тату, татуировки, татуировка]
  shop=tea: [чай, чайный, магазин, зеленый, черный]
  shop=toys: [игрушки, подарок, детям, детские, товары, конструктор, конструкторы, кукла, куклы]
  shop=travel_agency: [турагентство, тур, туризм, агентство, путешествия, билеты]
  shop=veg_food: [вегетарианцам, здоровое, питание, урбеч, соевое, молоко, каша, супы, веган, выганский, веганских, продукты, продуктов, магазин, веганам]

suggest_tags:
  # Page 1
  - shop=beauty
  - shop=instagram_beauty
  - shop=nail_salon
  - shop=hairdresser
  - shop=hair_salon
  - shop=skin_care
  - shop=tattoo
  - shop=massage
  - shop=cosmetics

  - shop=clothes
  - craft=dressmaker
  - craft=tailor
  - shop=florist
  - shop=jewelry
  - shop=shoes

  # Page 2
  - amenity=cafe
  - amenity=coffee
  - amenity=bar
  - amenity=fast_food
  - shop=convenience
  - shop=greengrocer
  - shop=veg_food
  - shop=alcohol
  - amenity=toilets

  - amenity=pharmacy
  - amenity=dentist
  - amenity=clinic
  - shop=chemist
  - shop=optician
  - leisure=fitness_centre

  # Page 3
  - amenity=school
  - amenity=childcare
  - amenity=art_school
  - amenity=music_school
  - amenity=language_school
  - amenity=dancing_school

  - shop=toys
  - shop=stationery
  - shop=craft
  - shop=pet
  - shop=outdoor
  - shop=car_parts

  - shop=electronics
  - shop=lighting
  - shop=electrical

  # Page 4
  - shop=fabric
  - shop=furniture
  - shop=curtain
  - shop=flooring
  - shop=doors
  - craft=roofer
  - craft=house
  - shop=bathroom_furnishing
  - craft=electronics_repair

  - amenity=bank
  - amenity=atm
  - office=insurance
  - office=property_management
  - office=company
  - shop=travel_agency

emoji:
  default: ❔
  shop=beauty: ✨
  shop=instagram_beauty: 🤳
  amenity=cafe: 🍴
  amenity=coffee: ☕
  shop=clothes: 👕
  shop=furniture: 🛋️
  office=company: 🏢
  shop=nail_salon: 💅
  shop=florist: 💐
  shop=travel_agency: ✈️
  shop=cosmetics: 💄
  shop=hairdresser: ✂️
  amenity=school: 📚
  amenity=childcare: 🧮
  amenity=pharmacy: 💊
  shop=convenience: 🛒
  shop=alcohol: 🍾
  amenity=toilets: 🚻
  amenity=art_school: 🎨
  shop=pet: 🐈
  shop=jewelry: 💎
  shop=hair_salon: 💇
  shop=doors: 🚪
  amenity=bar: 🍺
  shop=tea: 🍵
  craft=dressmaker: 👗
  shop=optician: 👓
